//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pest1._2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PestLocation
    {
        public int column_0 { get; set; }
        public string Scientific_Name { get; set; }
        public string Vernacular_name { get; set; }
        public string Event_Date__parsed { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
    }
}
